---
title: "EDA"
author: "Xin"
date: "2024-05-14"
output:
  pdf_document: default
  html_document: default
---
```{r}
library(electBook)
load("Irish.RData")
```

```{r}
head(Irish$indCons[,1:10])
```

```{r}
# Count zeros in each row
row_zero_counts <- rowSums(Irish$indCons == 0)

hist(row_zero_counts)
```

```{r}
sum(apply(Irish$indCons, 2, function(x) sum(x == 0)))
#There are many zeros in the demand data frame
print(16799*2674)
```

```{r}
# Count zeros in each column
col_zero_counts <- colSums(Irish$indCons == 0)

# Histogram of columns with more than 100 zeros
hist(col_zero_counts[col_zero_counts > 100], main="Histogram of Households with More Than 100 Zero Usage", xlab= "Zero Counts per Household")
```

```{r}
sum(col_zero_counts > 30*48)
```

```{r}
cols_to_remove <- which(col_zero_counts > 30*48)
```

```{r}
df0 <- Irish$indCons[,-cols_to_remove]

df0$time_mean_dem <- rowSums(Irish$indCons)/ncol(Irish$indCons)
```


```{r}
head(Irish$extra)
```

```{r}
df <- cbind(df0[,"time_mean_dem"],Irish$extra)
colnames(df) <- c("time_mean_demand", colnames(Irish$extra))
```







```{r}
head(df)
```

## Visualizing main characteristics

```{r}
# Load necessary libraries
library(ggplot2)
library(dplyr)

# Basic summary of each column
summary(df)
#`holy` is all FALSE

# Time series plot of time_mean_demand
ggplot(df, aes(x=dateTime, y=time_mean_demand)) + geom_line() + ggtitle("Time Series of Mean Demand")

# Boxplots to check variation of time_mean_demand across days of the week
ggplot(df, aes(x=dow, y=time_mean_demand)) + geom_boxplot() + ggtitle("Demand Variation by Day of Week")

```

```{r}
# Scatter plot of time_mean_demand vs. temperature
ggplot(df, aes(x=temp, y=time_mean_demand)) +
    geom_point(alpha=0.5) +
    geom_smooth(method="lm", se=FALSE, color="blue") +
    labs(x="Temperature", y="Mean Demand", title="Relationship Between Temperature and Mean Demand")
```
```{r}
# Line plot for time_mean_demand across different times of day
ggplot(df, aes(x=tod, y=time_mean_demand, group=1)) +
    geom_point(alpha=0.5) +
    geom_smooth(color="blue") +
    labs(x="Time of Day", y="Sum Demand", title="Mean Demand Across Different Times of Day")

```



